# Generated by Django 4.2.5 on 2023-09-21 15:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0004_empleado_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='observaciones',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
