# Generated by Django 4.2.5 on 2023-09-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0005_empleado_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fecha_nac',
            field=models.DateField(default='1960-1-1', verbose_name='Fecha de nacimiento'),
        ),
    ]
