# Generated by Django 4.2.5 on 2023-10-01 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0006_empleado_fecha_nac'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
