# Generated by Django 4.2.5 on 2023-10-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0007_empleado_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagen'),
        ),
    ]
