# Generated by Django 4.2.5 on 2023-11-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('descripcion', models.TextField(default='Descripción predeterminada')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('imagen', models.ImageField(null=True, upload_to='imagen')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
            },
        ),
    ]
