# Generated by Django 4.2.5 on 2024-05-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_categoria_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='imagen',
            field=models.CharField(default='default_image.png', max_length=250),
        ),
    ]
